import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";

const fira = Fira_Code({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fira.className}>
        <AuthContext>
        {children}
        </AuthContext>
      </body>
    </html>
  );
}
